### ISSUE TITLE
 "Enter" Button Refreshes Page Instead of Submitting Form

### ISSUE THREAD

**Issue by shyamtawli** [Haimantika/Contributing-guide-generator#5]
Currently, pressing the "Enter" key refreshes the page instead of generate button should be triggered.

**Comment by jagdishpatil02** [comment]
Hi @Haimantika , you can replace type="button" to type="submit "on this line to fix this issue `  <button type="button" id="generateButton"
              class="rounded-md bg-black px-3 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-black/80 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black">
              Generate
            </button>`

**Comment by Haimantika** [comment]
This is now done! Thanks @jagdishpatil02 :D and thanks @shyamtawli for raising the issue.
